### PR TITLE
Update mx-cleanup_hu.ts

### PR DESCRIPTION
**Pull request by ghost**
syntax typo at line 269: 1% -> %1

### CODE REVIEW

**Comment by AdrianTM** [comment]
Thanks, I will merge this, but it actually needs to be changed on Transifex (I did it)
Join the translation team if interested: https://app.transifex.com/anticapitalista/antix-development/translate/#hu

**Comment by vajdao** [comment]
@AdrianTM can you look into this please, because still the old typo'd translation is present on my main computer (which I updated couple of times since then)

Transifex, I'm registered there aswell, but I observed a huge delay of translations actually appearing on the installed systems, so I was like better edit it directly perhaps it will come off quicker. But thanks for the heads up.

**Comment by AdrianTM** [comment]
It's fixed, only that I didn't upgrade the package in the repo, the last build is from Nov 1, this change was made on Nov 6.

It's not quicker if you fix it here, it simply won't work, the build scripts will just pull the latest versions from transifex. Thanks for signing in there.

**Comment by AdrianTM** [comment]
Pushed a new build, it should fix this.

**Comment by vajdao** [comment]
Thank you, it did! Cheers :)

**Pull request merged**
